<Project>
    <ItemGroup Condition="'$(MSBuildProjectName)' != 'CyberBackup.Analyzer'">
        <ProjectReference Include="$(MSBuildThisFileDirectory)Libs/Analyze/CyberBackup.Analyzer/CyberBackup.Analyzer.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>
</Project>