services:
    postgres:
        image: postgres:16-alpine
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data

    minio:
        image: minio/minio:latest
        container_name: minio
        restart: unless-stopped
        command: server /data --console-address ":9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio_data:/data
        healthcheck:
            test: [ "CMD", "mc", "ready", "local" ]
            interval: 5s
            timeout: 5s
            retries: 10

    backend:
        build:
            context: ..
            dockerfile: backend/Apps/CyberBackup/Api/Dockerfile
        container_name: backend
        restart: unless-stopped
        ports:
            - "5000:8080"
        environment:
            - ASPNETCORE_URLS=http://+:8080
        
            - PostgresOptions__ConnectionString=Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=cyber-backup-api;Pooling=true;Minimum Pool Size=0;Maximum Pool Size=100;
            - PostgresOptions__AutoMigration=true

            - CyberCorsOptions__Origins__0=http://frontend
        
            - JwtOptions__Issuer=solution
            - JwtOptions__Audience=auth-api
            - JwtOptions__SigningKey=local-dev-signing-key-change-me-please-32-bytes-minimum
            - JwtOptions__AccessTokenLifetimeMinutes=15
        
            - RefreshTokenOptions__LifetimeDays=7
            - RefreshTokenOptions__TokenBytes=64
        
            - AuthTokenOptions__ClientId=web-client
            - AuthTokenOptions__Scopes__0=identity
        
            - PasswordHashOptions__Pepper=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
            - PasswordHashOptions__WorkFactor=12
        
            - SuperAdminOptions__Email=superadmin@example.com
            - SuperAdminOptions__Password=admin123
            - SuperAdminOptions__FullName=Суперадминистратор

            - MinioOptions__Endpoint=minio:9000
            - MinioOptions__AccessKey=minioadmin
            - MinioOptions__SecretKey=minioadmin
            - MinioOptions__BucketName=cyberbackup
            - MinioOptions__UseSsl=false
        depends_on:
            - postgres

    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        container_name: frontend
        restart: unless-stopped
        ports:
            - "80:80"
        depends_on:
            - backend

volumes:
    postgres_data:
    minio_data: